API/urls.py
from . import views
from django.urls import path
app_name = 'API'
from .views import *

"""
Per chiamare queste funzioni è necessario mettere nell'url prima la stringa http://127.0.0.1:5000/api/
"""
urlpatterns = [

    path('', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/find/<str:name>/', views.FindUser.as_view(), name='API-cerca-utente'),
    path('users/register/normaluser/', views.RegisterNormalUserFromMobilePhone.as_view(), name='API-registra-utente-normale'),
    path('users/register/shopuser/', views.RegisterShopUserFromMobilePhone.as_view(), name='API-registra-negozio'),
    path('users/profile/<int:pk>/', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/profile/', views.ModifyInfoLoginUser.as_view(), name='API-user-modify-info'),

    # per utente
    path('reviews_customer/<int:pk>/', views.ReturnReviewCustomer.as_view(), name='API-reviews-customer'),
    path('orders_customer/<int:pk>/', views.ReturnOrderCustomer.as_view(), name='API-orders-customer'),
    path('order_items_ref_code/<str:order_items_id>/', views.ReturnOrderItems.as_view(), name='API-orderitems-customer'),
    path('items_from_orderitems/<str:order_items_id>/', views.ReturnItemsFromOrderItems.as_view(), name='API-items-from-orderitemscustomer'),
    path('items_from_orderitems_filtered/<str:order_items_id>/<str:name_shop>/', views.ReturnItemsFromOrderItemsFiltered.as_view(), name='API-items-from-orderitemscustomer-filtered'),
    path('get_review_item/<str:order_item_id>/<str:item_selected_id>/', views.GetSingleReviewItem.as_view(), name='API-get-review-item-order'),
    path('leave_review_item/<str:order_item_id>/<str:item_selected_id>/', views.CreateReviewItem.as_view(), name='API-leave-review-item'),
    # path('orderitem_item/<str:order_items_id>/<str:id_shop>/', views.ReturnOrderItemsAndOrderItems.as_view(), name='API-orderitem-item'),
    path('check_existing_username/<str:username_to_check>/', check_existing_username),
    path('check_existing_username_ajax/', check_existing_username_ajax),

    # se devo aggiungere la mail prima controllo che non esista già un waituser con quell'username e quella password
    # e se non esiste lo creo e con un altro fetch aggiungo la password
    path('create_waituser/', views.CreateWaitUser.as_view(), name='API-create-waituser'),
    path('insert_email/<int:item_selected_id>/', views.InsertEmail.as_view(), name='API-insert-email'),



    # per Shop
    path('orders_shop/', views.ReturnOrderDoneByCustomer.as_view(), name='API-orders-shop'),
    path('items_booked/<str:order_items_id>/', views.ReturnItemsBooked.as_view(), name='API-items-shop'),
    path('travel_time/<str:username_shop>/', views.ReturnTimeUserShop, name='API-time-travel'),
    # path('upload_image/<str:id_shop>/', views.UploadItem.as_view(), name='API-upload-item'),
    path('insert_item/', views.InsertNewItem.as_view(), name='API-insert-item'),

    # *** review for/to shop
    path('review_shop/<str:username_shop>/', views.ReturnReviewShop.as_view(), name='API-review-shop'),
    path('review_from_customer_to_shop/<str:username_shop>/', views.CreateReviewForShop.as_view(), name='API-new-review-shop'),
    path('get_single_review_shop/<str:username_shop>/', views.GetSingleReviewShop.as_view(), name='API-get-single-review-left-to-shop'),

    # *** review for/to customer
    path('review_from_shop_to_customer/<int:id_user>/<int:id_order>/', views.CreateReviewForCustomer.as_view(),name='API-new-review-to-customer'),
    path('get_single_review_customer/<int:id_user>/<int:id_order>/', views.GetSingleReviewCustomer.as_view(),name='API-get-single-review-customer'),
    #

    # Vale
    path('items/list_all_items/', views.ListAllItems.as_view(), name='API-list-all-items'),
    path('items/<int:id_shop>/shop_all_items/', views.ShopAllItems.as_view(), name='API-shop-all-items'),
    path('items/<str:username_shop>/show_shop/', views.ShowShop.as_view(), name='API-show-shop'),
    path('items/<int:pk>/cart_orders/', views.CartOrders.as_view(), name='API-cart-orders'),
    path('id_items_from_orderitems/<int:pk>/', views.IdItemsFromOrderItems.as_view(), name='API-id-items-from-orderitems'),
    path('items/search/<int:pk>/<str:text>/', views.SearchItem.as_view(), name='API-search-item'),
    path('items/add_quantity/<int:pk>/<int:id_item>/<int:quantity>/', views.AddToCart.as_view(),
         name='API-add-to-cart'),

    path('items/<int:id_item>/delete/', views.DeleteItem.as_view(), name='API-delete-item-from-cart'),
    path('items/<int:id_item_to_delete>/deleteitemshop/', views.DeleteItemShop.as_view(), name='API-delete-item-shop'),
    path('items/<int:pk>/checkout/', views.Checkout, name='API-checkout'),
    path('items/<int:pk>/confirmcheckout/', views.ConfirmCheckout, name='API-confirm-checkout'),
    path('items/<int:id_item>/detail/', views.ItemDetail.as_view(), name='API-item-detail'),
    path('items/<int:id_item>/modifyitem/', views.ModifyItem.as_view(), name='API-modify-item'),
    # Fine

]

Marketplace/urls.py
from django.contrib import admin
#poichè si sta utilizzando Django >= 2.x si userà path e non url + pattern '' e non regexp r'^$' (analogamente nelle views)
from django.urls import path
from django.conf.urls import include    #aggiungo per poter usare la funzione include
from django.conf import settings
from django.conf.urls.static import static

# RICORDARSI: la / iniziale non va scritta all'inizio perchè si assume già inclusa nel path di grado inferiore
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),          #appena apro localhost:8000 parte la main.views
    path('users/', include('users.urls')),
    path('items/', include('items.urls')),
    path('review/', include('review.urls')),
    path('api/', include('API.urls')),

    path('api/rest-auth/', include("rest_auth.urls")),
    path('api/rest-auth/registration/', include("rest_auth.registration.urls")),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name = 'items'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    path('', views.item_page, name='item_page'),

    path('insert_item', views.insert_item, name='insert_item'),

    path('insert_email/<str:item_selected_id>', views.insert_email, name='insert_email'),

    path('<int:item_selected_id>/computeTime', views.computeTime, name='computeTime'),

    path('<int:item_selected_id>/show_feedback_item', views.show_feedback_item, name='show_feedback_item'),

    path('<int:shop_selected_id>/show_reviews_shop', views.show_reviews_shop, name='show_reviews_shop'),

    path('checkout', views.checkout, name='checkout'),

    path('<int:item_selected_id>/', views.buy_page, name='buy_page'),

    path('show_shop/<str:username_shop>', views.show_shop, name='show_shop'),

    #/annunci/#annuncio/modifica/
    path('<int:item_selected_id>/modify', views.modify_item, name='modify_item'),

    #/annunci/#annuncio/elimina/
    path('<int:item_selected_id>/delete', views.delete_item, name='delete_item'),

    #/annunci/#annuncio/add_to_cart/
    path('<int:item_selected_id>/add_to_cart', views.add_to_cart, name='add_to_cart'),

    path('go_to_cart', views.go_to_cart, name='go_to_cart'),

    path('<int:item_selected_id>/remove_single_item_from_cart', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),

    path('<int:item_selected_id>/remove_entire_item_from_cart', views.remove_entire_item_from_cart, name='remove_entire_item_from_cart'),

    path('view_order', views.view_order, name='view_order'),

    path('search/', views.search, name='search'),
]

review/urls.py
from django.urls import path
from . import views

app_name = 'review'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    path('show_items_to_review', views.show_items_to_review, name='show_items_to_review'),

    path('show_order_done_by_customer', views.show_order_done_by_customer, name='show_order_done_by_customer'),

    path('<int:item_selected_id>/<int:order_item_id>/add_review_item', views.add_review_item, name='add_review_item'),

    path('<int:item_selected_id>/<int:order_item_id>/show_item_reviewed', views.show_item_reviewed, name='show_item_reviewed'),

    path('<int:receiver_id>/<int:order_item_id>/show_customers_reviewed', views.show_customers_reviewed, name='show_customers_reviewed'),

    path('<int:shop_selected_id>/add_review_shop', views.add_review_shop, name='add_review_shop'),

    path('<int:order_id>/<int:customer_id>/add_review_customer', views.add_review_customer, name='add_review_customer'),


]

users/urls.py
#questo file non viene creato da django al momento della creazione dell'app ma deve essere creato manualmente
from django.urls import path
from . import views

app_name = 'users'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    # /users/login/
    path('login', views.login_all, name='login_all'),

    # /utenti/registrazione/
    # path('registration', views.registration, name='registration'),

    # path('test_login', views.test_login, name='test_login'),

    # /utenti/registrazione/normale
    path('normal_user_registration', views.normal_user_registration, name='normal_user_registration'),

    path('logout_user', views.logout_user, name='logout_user'),

    path('shop_registration', views.shop_registration, name='shop_registration'),
    path('modify_profile', views.modify_profile, name='modify_profile'),
    # path('modify_shop', views.modify_shop, name='modify_shop'),



    path('<int:oid>/prova_passaggio_interi', views.prova_passaggio_interi, name='prova_passaggio_interi'),
    path('insert_user_info', views.insert_user_info, name='insert_user_info'),
    path('insert_shop_info', views.insert_shop_info, name='insert_shop_info'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),


    path('home_for_user', views.home_for_user, name='home_for_user'),
    path('home_for_shop', views.home_for_shop, name='home_for_shop'),
    # path('prova_registrazione', views.prova_registrazione, name='prova_registrazione'),

    # /utenti/logout/
    #path('logout', views.logout, name='logout'),

]

review/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import re
from items.models import OrderItem
from . import models
from django import forms


class ReviewItemForm(ModelForm):
    # per formattazione errori e richieste (vedi documentazione Django)
    required_css_class = 'required'

    class Meta:
        model = models.ReviewItem
        fields = [
            'title_of_comment',
            'description',
            'rating'
        ]

    def __init__(self, *args, **kwargs):
        reviewed = kwargs.pop('reviewed')
        super(ReviewItemForm, self).__init__(*args, **kwargs)
        if reviewed:
            self.fields['title_of_comment'].widget.attrs['readonly'] = True
            self.fields['description'].widget.attrs['readonly'] = True
            self.fields['rating'].widget.attrs['readonly'] = True

    def clean_title_of_comment(self):
        if not re.match("^[A-Za-z0-9., 'èòàùì]+$", self.cleaned_data['title_of_comment']):
            raise ValidationError(_('Errore: il campo titolo può contenere solo lettere e numeri.'))
        if not (3 <= len(self.cleaned_data['title_of_comment']) <= 50):
            raise ValidationError(_('Errore: il campo titolo deve avere lunghezza fra 3 e 50 caratteri.'))
        return self.cleaned_data['title_of_comment']

    def clean_description(self):
        # controllo descrizione
        if not re.match("^[A-Za-z0-9., 'èòàùì]+$", self.cleaned_data['description']):
            raise ValidationError(
                _('Errore: il campo descrizione può contenere solo lettere, numeri, punti, virgole e spazi.'))
        if not (3 <= len(self.cleaned_data['description']) <= 50):
            raise ValidationError(_('Errore: il campo descrizione deve avere lunghezza fra 3 e 50 caratteri.'))
        return self.cleaned_data['description']


class ReviewShopForm(ModelForm):
    # per formattazione errori e richieste (vedi documentazione Django)
    required_css_class = 'required'

    class Meta:
        model = models.ReviewShop
        fields = [
            'title_of_comment',
            'description',
            'rating'
        ]

    def clean_title_of_comment(self):
        if not re.match("^[A-Za-z0-9., 'èòàùì]+$", self.cleaned_data['title_of_comment']):
            raise ValidationError(_('Errore: il campo titolo può contenere solo lettere e numeri.'))
        if not (3 <= len(self.cleaned_data['title_of_comment']) <= 50):
            raise ValidationError(_('Errore: il campo titolo deve avere lunghezza fra 3 e 50 caratteri.'))
        return self.cleaned_data['title_of_comment']

    def clean_description(self):
        # controllo descrizione
        if not re.match("^[A-Za-z0-9., 'èòàùì]+$", self.cleaned_data['description']):
            raise ValidationError(
                _('Errore: il campo descrizione può contenere solo lettere, numeri, punti, virgole e spazi.'))
        if not (3 <= len(self.cleaned_data['description']) <= 50):
            raise ValidationError(_('Errore: il campo descrizione deve avere lunghezza fra 3 e 50 caratteri.'))
        return self.cleaned_data['description']

class ReviewCustomerForm(ModelForm):
    # per formattazione errori e richieste (vedi documentazione Django)
    required_css_class = 'required'

    class Meta:
        model = models.ReviewCustomer
        fields = [
            'title_of_comment',
            'description',
            'rating'
        ]

    def __init__(self, *args, **kwargs):
        reviewed = kwargs.pop('reviewed')
        super(ReviewCustomerForm, self).__init__(*args, **kwargs)
        if reviewed:
            self.fields['title_of_comment'].widget.attrs['readonly'] = True
            self.fields['description'].widget.attrs['readonly'] = True
            self.fields['rating'].widget.attrs['readonly'] = True

    def clean_title_of_comment(self):
        if not re.match("^[A-Za-z0-9., 'èòàùì]+$", self.cleaned_data['title_of_comment']):
            raise ValidationError(_('Errore: il campo titolo può contenere solo lettere e numeri.'))
        if not (3 <= len(self.cleaned_data['title_of_comment']) <= 50):
            raise ValidationError(_('Errore: il campo titolo deve avere lunghezza fra 3 e 50 caratteri.'))
        return self.cleaned_data['title_of_comment']

    def clean_description(self):
        # controllo descrizione
        if not re.match("^[A-Za-z0-9., 'èòàùì]+$", self.cleaned_data['description']):
            raise ValidationError(
                _('Errore: il campo descrizione può contenere solo lettere, numeri, punti, virgole e spazi.'))
        if not (3 <= len(self.cleaned_data['description']) <= 50):
            raise ValidationError(_('Errore: il campo descrizione deve avere lunghezza fra 3 e 50 caratteri.'))
        return self.cleaned_data['description']

review/templates/review/add_review_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Aggiungi Recensione{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block menu_id %}
    <li><a href="{% url 'users:home_for_user' %}">Home</a></li>
    {% endblock %}

    {% block cart %}
    <a href="{% url 'items:go_to_cart' %}" class="nav-link waves-effect">
        <span class="badge bg-danger bg-secondary">
            {% if all_items.ordered != 1 %}
                {% if all_items == 0 %}0{% endif %}
                {% if all_items.get_final_quantity >= 0%}{{ all_items.get_final_quantity}}{% endif %}
            {% endif %}
            {% if all_items.ordered == 1 %}0{% endif %}
        </span>
        <img src="{% static 'images/cart.png'%}" width="30px" height="30px">
    </a>
    {% endblock %}

    {% block add_review_item %}

<!--    FUNZIONI E NOMI DI FUNZIONI SOTTOSTANTI IN HTML DA CONTROLLARE [MODIFICA] -->

    <div class="modify_user_page">
      <div class="container">
          <div class="row">
              <div class="col-2">
                  <div class="form_container_add_review">
                      <div class="form-btn">
                          <span>Aggiungi una Recensione</span>
                      </div>
                      <form id="RegFormReview" action="{% url 'review:add_review_item' item_selected_id=item_selected_id order_item_id=order_item_id%}" method="post">
                        {% for field in review_form %}
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                                <label class="control-label col-sm-2" for="users">{{ field.label_tag }}</label>
                                <div class="col-sm-10" > {{ field }}</div>
                            </div>
                        {% endfor %}
                    <button type="submit" class="btn_modify">Aggiungi Recensione</button>
                    </form>
                    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
                    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
                    <script type="text/javascript" src="{% static 'review_form_validator.js' %}"></script>
                  </div>
              </div>
          </div>
      </div>
    </div>
    {% endblock %}
</body>
</html>

review/templates/review/add_review_shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Aggiungi Recensione{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block menu_id %}
    <li><a href="{% url 'users:home_for_user' %}">Home</a></li>
    {% endblock %}

    {% block cart %}
    <a href="{% url 'items:go_to_cart' %}" class="nav-link waves-effect">
        <span class="badge bg-danger bg-secondary">
            {% if all_items.ordered != 1 %}
                {% if all_items == 0 %}0{% endif %}
                {% if all_items.get_final_quantity >= 0%}{{ all_items.get_final_quantity}}{% endif %}
            {% endif %}
            {% if all_items.ordered == 1 %}0{% endif %}
        </span>
        <img src="{% static 'images/cart.png'%}" width="30px" height="30px">
    </a>
    {% endblock %}

    {% block add_review_shop %}
<!--    FUNZIONI E NOMI DI FUNZIONI SOTTOSTANTI IN HTML DA CONTROLLARE [MODIFICA] -->

    <div class="modify_user_page">
      <div class="container">
          <div class="row">
              <div class="col-2">
                  <div class="form_container_add_review">
                      <div class="form-btn">
                          <span>Aggiungi Recensione per il negozio</span>
                      </div> <form id="RegFormUser2" action="{% url 'review:add_review_shop' shop_selected_id=shop_to_review.id%}" method="post">
                    {% for field in review_form %}
                        {% csrf_token %}
                        <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                        <span class="text-danger small">{{ field.errors }}</span>
                        </div>
                        <label class="control-label col-sm-2" for="users">{{ field.label_tag }}</label>
                        <div class="col-sm-10" > {{ field }}</div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn_modify">Aggiungi Recensione</button>
                    </form>
                    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
                    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
                    <script type="text/javascript" src="{% static 'review_form_validator.js' %}"></script>
                  </div>
              </div>
          </div>
      </div>
    </div>
    {% endblock %}
</body>
</html>

review/templates/review/mostra_ordini_fatti.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Mostra Ordini Fatti{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block menu_id %}
    <li><a href="{% url 'users:home_for_user' %}">Home</a></li>
    <li><a href="{% url 'items:view_order' %}">View Order</a></li>
    {% endblock %}

    {% block cart %}
    <a href="{% url 'items:go_to_cart' %}" class="nav-link waves-effect">
        <span class="badge bg-danger bg-secondary">
            {% if all_items.ordered != 1 %}
                {% if all_items == 0 %}0{% endif %}
                {% if all_items.get_final_quantity >= 0%}{{ all_items.get_final_quantity}}{% endif %}
            {% endif %}
            {% if all_items.ordered == 1 %}0{% endif %}
        </span>
        <img src="{% static 'images/cart.png'%}" width="30px" height="30px">
    </a>
    {% endblock %}

    {% block item_page %}
    <main>
        <div class="container">
            <div class="container text-center">
                {% if user.user is not None %}
                    <h2 id="title">Welcome: {{ user }}</h2>
                {% endif %}
            </div>
    <!------------------------------ SEZIONE ELENCO PRODOTTI ----------------------------------------->
            <section class="text-center mb-4">
                <div class="row wow fadeIn">
                {% for single_order in order_item %}
                    <div class="col-lg-3 col-md-6 mb-4">
                        <div class="card" style="width: 18rem;">
                                <img id="img_no_gray" src="{{ single_order.item.image.url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ single_order.item.name }}</h5>
                                <p class="lead">
                                  <span>€ {{ single_order.item.price }}</span>
                                </p>
                                <h5>Quantità acquistate: {{ single_order.quantity }}</h5>

                                {% if single_order.review_item_done %}
                                <p  style="color:green">Recensione effettuata</p>
                                <p class="card-text">{{ single_order.item.category }}</p>
                                <a href="{% url 'review:show_item_reviewed' item_selected_id=single_order.item.id order_item_id=single_order.id%}" class="btn btn-primary">Guarda la recensione</a>
                                {% else %}
                                <p  style="color:red">Recensione da lasciare</p>
                                <p class="card-text">{{ single_order.item.category }}</p>
                                <a href="{% url 'review:add_review_item' item_selected_id=single_order.item.id order_item_id=single_order.id%}" class="btn btn-primary">Lascia una recensione</a>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </section>
        </div>
    </main>
    {% endblock %}
</body>
</html>