API/urls.py
from . import views
from django.urls import path
app_name = 'API'
from .views import *

"""
Per chiamare queste funzioni è necessario mettere nell'url prima la stringa http://127.0.0.1:5000/api/
"""
urlpatterns = [

    path('', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/find/<str:name>/', views.FindUser.as_view(), name='API-cerca-utente'),
    path('users/register/normaluser/', views.RegisterNormalUserFromMobilePhone.as_view(), name='API-registra-utente-normale'),
    path('users/register/shopuser/', views.RegisterShopUserFromMobilePhone.as_view(), name='API-registra-negozio'),
    path('users/profile/<int:pk>/', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/profile/', views.ModifyInfoLoginUser.as_view(), name='API-user-modify-info'),

    # per utente
    path('reviews_customer/<int:pk>/', views.ReturnReviewCustomer.as_view(), name='API-reviews-customer'),
    path('orders_customer/<int:pk>/', views.ReturnOrderCustomer.as_view(), name='API-orders-customer'),
    path('order_items_ref_code/<str:order_items_id>/', views.ReturnOrderItems.as_view(), name='API-orderitems-customer'),
    path('items_from_orderitems/<str:order_items_id>/', views.ReturnItemsFromOrderItems.as_view(), name='API-items-from-orderitemscustomer'),
    path('items_from_orderitems_filtered/<str:order_items_id>/<str:name_shop>/', views.ReturnItemsFromOrderItemsFiltered.as_view(), name='API-items-from-orderitemscustomer-filtered'),
    path('get_review_item/<str:order_item_id>/<str:item_selected_id>/', views.GetSingleReviewItem.as_view(), name='API-get-review-item-order'),
    path('leave_review_item/<str:order_item_id>/<str:item_selected_id>/', views.CreateReviewItem.as_view(), name='API-leave-review-item'),
    # path('orderitem_item/<str:order_items_id>/<str:id_shop>/', views.ReturnOrderItemsAndOrderItems.as_view(), name='API-orderitem-item'),
    path('check_existing_username/<str:username_to_check>/', check_existing_username),
    path('check_existing_username_ajax/', check_existing_username_ajax),

    # se devo aggiungere la mail prima controllo che non esista già un waituser con quell'username e quella password
    # e se non esiste lo creo e con un altro fetch aggiungo la password
    path('create_waituser/', views.CreateWaitUser.as_view(), name='API-create-waituser'),
    path('insert_email/<int:item_selected_id>/', views.InsertEmail.as_view(), name='API-insert-email'),



    # per Shop
    path('orders_shop/', views.ReturnOrderDoneByCustomer.as_view(), name='API-orders-shop'),
    path('items_booked/<str:order_items_id>/', views.ReturnItemsBooked.as_view(), name='API-items-shop'),
    path('travel_time/<str:username_shop>/', views.ReturnTimeUserShop, name='API-time-travel'),
    # path('upload_image/<str:id_shop>/', views.UploadItem.as_view(), name='API-upload-item'),
    path('insert_item/', views.InsertNewItem.as_view(), name='API-insert-item'),

    # *** review for/to shop
    path('review_shop/<str:username_shop>/', views.ReturnReviewShop.as_view(), name='API-review-shop'),
    path('review_from_customer_to_shop/<str:username_shop>/', views.CreateReviewForShop.as_view(), name='API-new-review-shop'),
    path('get_single_review_shop/<str:username_shop>/', views.GetSingleReviewShop.as_view(), name='API-get-single-review-left-to-shop'),

    # *** review for/to customer
    path('review_from_shop_to_customer/<int:id_user>/<int:id_order>/', views.CreateReviewForCustomer.as_view(),name='API-new-review-to-customer'),
    path('get_single_review_customer/<int:id_user>/<int:id_order>/', views.GetSingleReviewCustomer.as_view(),name='API-get-single-review-customer'),
    #

    # Vale
    path('items/list_all_items/', views.ListAllItems.as_view(), name='API-list-all-items'),
    path('items/<int:id_shop>/shop_all_items/', views.ShopAllItems.as_view(), name='API-shop-all-items'),
    path('items/<str:username_shop>/show_shop/', views.ShowShop.as_view(), name='API-show-shop'),
    path('items/<int:pk>/cart_orders/', views.CartOrders.as_view(), name='API-cart-orders'),
    path('id_items_from_orderitems/<int:pk>/', views.IdItemsFromOrderItems.as_view(), name='API-id-items-from-orderitems'),
    path('items/search/<int:pk>/<str:text>/', views.SearchItem.as_view(), name='API-search-item'),
    path('items/add_quantity/<int:pk>/<int:id_item>/<int:quantity>/', views.AddToCart.as_view(),
         name='API-add-to-cart'),

    path('items/<int:id_item>/delete/', views.DeleteItem.as_view(), name='API-delete-item-from-cart'),
    path('items/<int:id_item_to_delete>/deleteitemshop/', views.DeleteItemShop.as_view(), name='API-delete-item-shop'),
    path('items/<int:pk>/checkout/', views.Checkout, name='API-checkout'),
    path('items/<int:pk>/confirmcheckout/', views.ConfirmCheckout, name='API-confirm-checkout'),
    path('items/<int:id_item>/detail/', views.ItemDetail.as_view(), name='API-item-detail'),
    path('items/<int:id_item>/modifyitem/', views.ModifyItem.as_view(), name='API-modify-item'),
    # Fine

]

Marketplace/urls.py
from django.contrib import admin
#poichè si sta utilizzando Django >= 2.x si userà path e non url + pattern '' e non regexp r'^$' (analogamente nelle views)
from django.urls import path
from django.conf.urls import include    #aggiungo per poter usare la funzione include
from django.conf import settings
from django.conf.urls.static import static

# RICORDARSI: la / iniziale non va scritta all'inizio perchè si assume già inclusa nel path di grado inferiore
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),          #appena apro localhost:8000 parte la main.views
    path('users/', include('users.urls')),
    path('items/', include('items.urls')),
    path('review/', include('review.urls')),
    path('api/', include('API.urls')),

    path('api/rest-auth/', include("rest_auth.urls")),
    path('api/rest-auth/registration/', include("rest_auth.registration.urls")),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name = 'items'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    path('', views.item_page, name='item_page'),

    path('insert_item', views.insert_item, name='insert_item'),

    path('insert_email/<str:item_selected_id>', views.insert_email, name='insert_email'),

    path('<int:item_selected_id>/computeTime', views.computeTime, name='computeTime'),

    path('<int:item_selected_id>/show_feedback_item', views.show_feedback_item, name='show_feedback_item'),

    path('<int:shop_selected_id>/show_reviews_shop', views.show_reviews_shop, name='show_reviews_shop'),

    path('checkout', views.checkout, name='checkout'),

    path('<int:item_selected_id>/', views.buy_page, name='buy_page'),

    path('show_shop/<str:username_shop>', views.show_shop, name='show_shop'),

    #/annunci/#annuncio/modifica/
    path('<int:item_selected_id>/modify', views.modify_item, name='modify_item'),

    #/annunci/#annuncio/elimina/
    path('<int:item_selected_id>/delete', views.delete_item, name='delete_item'),

    #/annunci/#annuncio/add_to_cart/
    path('<int:item_selected_id>/add_to_cart', views.add_to_cart, name='add_to_cart'),

    path('go_to_cart', views.go_to_cart, name='go_to_cart'),

    path('<int:item_selected_id>/remove_single_item_from_cart', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),

    path('<int:item_selected_id>/remove_entire_item_from_cart', views.remove_entire_item_from_cart, name='remove_entire_item_from_cart'),

    path('view_order', views.view_order, name='view_order'),

    path('search/', views.search, name='search'),
]

review/urls.py
from django.urls import path
from . import views

app_name = 'review'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    path('show_items_to_review', views.show_items_to_review, name='show_items_to_review'),

    path('show_order_done_by_customer', views.show_order_done_by_customer, name='show_order_done_by_customer'),

    path('<int:item_selected_id>/<int:order_item_id>/add_review_item', views.add_review_item, name='add_review_item'),

    path('<int:item_selected_id>/<int:order_item_id>/show_item_reviewed', views.show_item_reviewed, name='show_item_reviewed'),

    path('<int:receiver_id>/<int:order_item_id>/show_customers_reviewed', views.show_customers_reviewed, name='show_customers_reviewed'),

    path('<int:shop_selected_id>/add_review_shop', views.add_review_shop, name='add_review_shop'),

    path('<int:order_id>/<int:customer_id>/add_review_customer', views.add_review_customer, name='add_review_customer'),


]

users/urls.py
#questo file non viene creato da django al momento della creazione dell'app ma deve essere creato manualmente
from django.urls import path
from . import views

app_name = 'users'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    # /users/login/
    path('login', views.login_all, name='login_all'),

    # /utenti/registrazione/
    # path('registration', views.registration, name='registration'),

    # path('test_login', views.test_login, name='test_login'),

    # /utenti/registrazione/normale
    path('normal_user_registration', views.normal_user_registration, name='normal_user_registration'),

    path('logout_user', views.logout_user, name='logout_user'),

    path('shop_registration', views.shop_registration, name='shop_registration'),
    path('modify_profile', views.modify_profile, name='modify_profile'),
    # path('modify_shop', views.modify_shop, name='modify_shop'),



    path('<int:oid>/prova_passaggio_interi', views.prova_passaggio_interi, name='prova_passaggio_interi'),
    path('insert_user_info', views.insert_user_info, name='insert_user_info'),
    path('insert_shop_info', views.insert_shop_info, name='insert_shop_info'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),


    path('home_for_user', views.home_for_user, name='home_for_user'),
    path('home_for_shop', views.home_for_shop, name='home_for_shop'),
    # path('prova_registrazione', views.prova_registrazione, name='prova_registrazione'),

    # /utenti/logout/
    #path('logout', views.logout, name='logout'),

]

items/forms.py
import magic
from django import forms
from .models import Item, WaitUser
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import re

MIME_TYPES = ['image/jpeg', 'image/png']


class WaitUserForm(ModelForm):
    # email = forms.EmailField(max_length=100)
    email = forms.EmailField(widget=forms.Textarea(attrs={'cols': 20, 'rows': 1}))

    class Meta:
        model = WaitUser
        fields = ['email']

    def clean_email(self):
        if not (5 <= len(self.cleaned_data['email']) <= 100):
            raise ValidationError(_('Errore: la mail deve essere compresa gra 5 e 100 caratteri.'))
        return self.cleaned_data['email']


class ItemForm(ModelForm):
    required_css_class = 'required'
    name = forms.CharField(max_length=95)
    price = forms.FloatField()
    discount_price = forms.FloatField(required=True)
    choice_category = (('Abbigliamento', 'Abbigliamento'), ('Tecnologia', 'Tecnologia'), ('Sport', 'Sport'),
                       ('Casa', 'Casa'), ('Motori', 'Motori'))
    category = forms.ChoiceField(choices=choice_category)
    quantity = forms.IntegerField()
    description = forms.CharField(widget=forms.Textarea)
    #data_inizio = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    #data_fine = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    image = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['discount_price'].required = False

    class Meta:
        model = Item
        fields = ['name', 'price', 'discount_price', 'category', 'quantity', 'description', 'image']

    def clean_name(self):
        if not re.match("^[A-Za-z0-9 .,'èòàùì]+$", self.cleaned_data['name']):
            raise ValidationError(_('Errore: il nome può contenere solo lettere, numeri e spazi.'))
        if not (1 <= len(self.cleaned_data['name']) <= 95):
            raise ValidationError(_('Errore: il nome deve avere lunghezza fra 1 e 95 caratteri.'))
        return self.cleaned_data['name']

    def clean_price(self):
        if not (0 <= self.cleaned_data['price'] <= 10000000):
            raise ValidationError(_('Errore: inserire un prezzo valido.'))
        return self.cleaned_data['price']

    def clean_discount_price(self):
        print(self.cleaned_data['discount_price'])
        if self.cleaned_data['discount_price'] is not None:
            if not (0 <= self.cleaned_data['discount_price'] <= 10000000):
                raise ValidationError(_('Errore: inserire un prezzo valido.'))
        return self.cleaned_data['discount_price']

    def clean_description(self):
        # controllo descrizione
        if not re.match("^[A-Za-z0-9 .,'èòàùì]+$", self.cleaned_data['description']):
            raise ValidationError(_('Errore: la descrizione può contenere solo lettere, '
                                    'numeri, punti, virgole e spazi.'))
        if not (3 <= len(self.cleaned_data['description']) <= 50):
            raise ValidationError(_('Errore: la descrizione deve avere lunghezza fra 3 e 50 caratteri.'))
        return self.cleaned_data['description']

    def clean_quantity(self):
        if not re.match("^[0-9]+$", str(self.cleaned_data['quantity'])):
            raise ValidationError(_('Errore: inserire una quantità valida.'))
        return self.cleaned_data['quantity']

    def clean_image(self):
        files = self.files.get('image')
        if files is not None:
            file_size = files.size
            limit_MB = 5
            if file_size > limit_MB * 1024 * 1024:
                raise ValidationError("La dimensione massima per le immagini è %s MB" % limit_MB)
            file_type = magic.from_buffer(files.read(), mime=True)
            if file_type not in MIME_TYPES:
                raise forms.ValidationError(_("file non supportato."))
            return files
        return None

items/templates/items/add_to_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Add_To_Cart{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block menu_id %}
    <li><a href="{% url 'users:home_for_user' %}">Home</a></li>
    {% endblock %}

    {% block cart %}
    <a href="{% url 'items:go_to_cart' %}" class="nav-link waves-effect">
        <span class="badge bg-danger bg-secondary">
            {% if order_item.ordered != 1 %}
                {% if all_items == 0 %}0{% endif %}
                {% if all_items.get_final_quantity >= 0%}{{ all_items.get_final_quantity}}{% endif %}
            {% endif %}
            {% if order_item.ordered == 1 %}0{% endif %}
        </span>
        <img src="{% static 'images/cart.png'%}" width="30px" height="30px">
    </a>
    {% endblock %}

{% block add_to_cart %}
    <div class="container_add_to_cart">
        <div id="cart_top" class="table-responsive text-nowrap">
        <h2>Oggetti nel carrello</h2>
        <table class="table">
            <thead class="thead_cart">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Discount Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            {% if order_item.ordered != 1 %}
                {% for order_item in all_items.items.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order_item.item.name }}</td>
                        <td>{{ order_item.item.price }} €</td>
                        <td>{{ order_item.item.discount_price }} €</td>
                        <td>{{ order_item.quantity }}</td>
                        <td>
                        {% if order_item.item.discount_price %}
                            {{ order_item.get_total_discount_item_price }} €
                            <span class="badge badge-primary">Saving €{{ order_item.get_amount_saved }}</span>
                        {% else %}
                            ${{ order_item.get_total_item_price }}
                        {% endif %}
                        <td><a class="btn_cart" href="{% url 'items:remove_single_item_from_cart' item_selected_id=order_item.item.id%}" class="button">Cancella</a></td>
                        {% if order_item.quantity > 1%}
                            <td><a class="btn_cart" href="{% url 'items:remove_entire_item_from_cart' item_selected_id=order_item.item.id%}" class="button">Cancella Tutto</a><td>
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>
        <div class="col-md-12 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="badge badge-secondary badge-pill">{{ all_items.items.count }}</span>
        </h4>
        <ul class="list-group mb-3 z-depth-1">
        {% if order_item.ordered != 1 %}
            {% for order_item in all_items.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.name}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
                </div>
                <span class="text-muted">{{ order_item.get_final_price }} €</span>
            </li>
            {% endfor %}
        {% endif %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Totale</span>
            <strong>{{ all_items.get_total }} €</strong>
        </li>
        </ul>
    </div>
        <td colspan="5">

            {% if allowed_to_buy %}
                <a class='btn' href="{% url 'items:checkout'%}">Procedi al checkout</a>
            {% else %}
                <a class='btn'>Attendi {{data_fine_blocco}}</a>
            {% endif %}
            <a class='btn' href="{% url 'items:item_page'%}">Fai altri acquisti</a>
        </td>
        </div>
    </div>

{% endblock %}
</body>
</html>

items/templates/items/base_aggiungi_item.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
        <div class="col-sm-10" id="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

items/templates/items/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Add_To_Cart{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block menu_id %}
    <li><a href="{% url 'users:home_for_user' %}">Home</a></li>
    {% endblock %}

    {% block cart %}
    <a href="{% url 'items:go_to_cart' %}" class="nav-link waves-effect">
        <span class="badge bg-danger bg-secondary">
            {% if all_items.ordered != 1 %}
                {% if all_items == 0 %}0{% endif %}
                {% if all_items.get_final_quantity >= 0%}{{ all_items.get_final_quantity}}{% endif %}
            {% endif %}
            {% if all_items.ordered == 1 %}0{% endif %}
        </span>
        <img src="{% static 'images/cart.png'%}" width="30px" height="30px">
    </a>
    {% endblock %}

    {% block checkout %}
        <br>
        <br>
        <br>
        <br>
    <div class="container_order">
        <div class="empty-container">
                <div class="col-empty">
                    <div class="row-empty-1">
                        <img src="{% static 'images/check.png' %}" class="empty_cart-img">
                    </div>
                    <div class="row-empty-2">
                        <h1>Congratulazioni, il tuo ordine è stato salvato!</h1>
                        <h4>Il tuo ref code è: {{ref_code}}<br>
                        </h4>
                    </div>
                    <div class="row-empty-3">
                        <a class='btn btn-primary float-right' href="{% url 'items:item_page'%}">Fai altri acquisti</a>
                        <a class='btn btn-primary float-right' href="{% url 'items:view_order'%}">Visualizza ordini</a>
                    </div>
                </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

items/templates/items/insert.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

items/templates/items/item_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Item_Page{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block menu_id %}
    <li><a href="{% url 'users:home_for_user' %}">Home</a></li>
    <li><a href="{% url 'items:view_order' %}">View Order</a></li>
    {% endblock %}

    {% block cart %}
    <a href="{% url 'items:go_to_cart' %}" class="nav-link waves-effect">
        <span class="badge bg-danger bg-secondary">{% if all_items_cart == 0 %}0{% endif %}{% if all_items_cart.get_final_quantity >= 0%}{{ all_items_cart.get_final_quantity}}{% endif %}</span>
        <img src="{% static 'images/cart.png'%}" width="30px" height="30px">
    </a>
    {% endblock %}

    {% block item_page %}
    <main>
        <div class="container">
            <div class="container text-center">
                {% if user.user is not None %}
                    <h3 id="title">Benvenuto: {{ user }}</h3>
                {% endif %}
            </div>
    <!------------------------------ NAVBAR +FILTRO ----------------------------------------->
        <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
            <div class="small-container">
                <form class="d-flex" method="get" action="{% url 'items:search'%}">
                    <input name="search" id="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button id="search_button" class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    <!------------------------------ SEZIONE ELENCO PRODOTTI ----------------------------------------->
        <section class="text-center mb-4">
            <div class="row wow fadeIn">
            {% for item in all_items %}
                <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card" style="width: 18rem;">
                        {% if item.quantity > 0 %}
                            <img id="img_no_gray" src="{{ item.image.url }}" class="card-img-top" alt="...">
                        {% else %}
                            <img id="gray_no_quantity" src="{{ item.image.url }}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <h5 class="lead">
                              {% if item.discount_price %}
                              <span class="mr-1">
                                <del>€{{ item.price }}</del>
                              </span>
                              <span>€{{ item.discount_price }}</span>
                              {% else %}
                              <span>€{{ item.price }}</span>
                              {% endif %}
                            </h5>
                            <h5>Negozio: {{ item.user.username }}</h5>
                            <h5 class="card-text">{{ item.category }}</h5>
                                {% if item.quantity <= 0 %}
                                <h5>Quantità: {{ item.quantity }}</h5>
                                <a href="{% url 'items:buy_page' item_selected_id=item.id %}" class="btn_card">Inserisci Email</a>
                                <a href="{% url 'items:show_shop' username_shop=item.user.username%}" class="btn_card">Visita Negozio</a>
                                {% endif %}
                                {% if item.quantity > 0 %}
                                <h5>Quantità: {{ item.quantity }}</h5>
                                <a href="{% url 'items:buy_page' item_selected_id=item.id %}" id="acquista_btn" class="btn_card">Acquista</a>
                                <a href="{% url 'items:show_shop' username_shop=item.user.username%}" class="btn_card">Visita Negozio</a>
                                {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </section>
        </div>
    </main>
    {% endblock %}
</body>
</html>