API/urls.py
from . import views
from django.urls import path
app_name = 'API'
from .views import *

"""
Per chiamare queste funzioni è necessario mettere nell'url prima la stringa http://127.0.0.1:5000/api/
"""
urlpatterns = [

    path('', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/find/<str:name>/', views.FindUser.as_view(), name='API-cerca-utente'),
    path('users/register/normaluser/', views.RegisterNormalUserFromMobilePhone.as_view(), name='API-registra-utente-normale'),
    path('users/register/shopuser/', views.RegisterShopUserFromMobilePhone.as_view(), name='API-registra-negozio'),
    path('users/profile/<int:pk>/', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/profile/', views.ModifyInfoLoginUser.as_view(), name='API-user-modify-info'),

    # per utente
    path('reviews_customer/<int:pk>/', views.ReturnReviewCustomer.as_view(), name='API-reviews-customer'),
    path('orders_customer/<int:pk>/', views.ReturnOrderCustomer.as_view(), name='API-orders-customer'),
    path('order_items_ref_code/<str:order_items_id>/', views.ReturnOrderItems.as_view(), name='API-orderitems-customer'),
    path('items_from_orderitems/<str:order_items_id>/', views.ReturnItemsFromOrderItems.as_view(), name='API-items-from-orderitemscustomer'),
    path('items_from_orderitems_filtered/<str:order_items_id>/<str:name_shop>/', views.ReturnItemsFromOrderItemsFiltered.as_view(), name='API-items-from-orderitemscustomer-filtered'),
    path('get_review_item/<str:order_item_id>/<str:item_selected_id>/', views.GetSingleReviewItem.as_view(), name='API-get-review-item-order'),
    path('leave_review_item/<str:order_item_id>/<str:item_selected_id>/', views.CreateReviewItem.as_view(), name='API-leave-review-item'),
    # path('orderitem_item/<str:order_items_id>/<str:id_shop>/', views.ReturnOrderItemsAndOrderItems.as_view(), name='API-orderitem-item'),
    path('check_existing_username/<str:username_to_check>/', check_existing_username),
    path('check_existing_username_ajax/', check_existing_username_ajax),

    # se devo aggiungere la mail prima controllo che non esista già un waituser con quell'username e quella password
    # e se non esiste lo creo e con un altro fetch aggiungo la password
    path('create_waituser/', views.CreateWaitUser.as_view(), name='API-create-waituser'),
    path('insert_email/<int:item_selected_id>/', views.InsertEmail.as_view(), name='API-insert-email'),



    # per Shop
    path('orders_shop/', views.ReturnOrderDoneByCustomer.as_view(), name='API-orders-shop'),
    path('items_booked/<str:order_items_id>/', views.ReturnItemsBooked.as_view(), name='API-items-shop'),
    path('travel_time/<str:username_shop>/', views.ReturnTimeUserShop, name='API-time-travel'),
    # path('upload_image/<str:id_shop>/', views.UploadItem.as_view(), name='API-upload-item'),
    path('insert_item/', views.InsertNewItem.as_view(), name='API-insert-item'),

    # *** review for/to shop
    path('review_shop/<str:username_shop>/', views.ReturnReviewShop.as_view(), name='API-review-shop'),
    path('review_from_customer_to_shop/<str:username_shop>/', views.CreateReviewForShop.as_view(), name='API-new-review-shop'),
    path('get_single_review_shop/<str:username_shop>/', views.GetSingleReviewShop.as_view(), name='API-get-single-review-left-to-shop'),

    # *** review for/to customer
    path('review_from_shop_to_customer/<int:id_user>/<int:id_order>/', views.CreateReviewForCustomer.as_view(),name='API-new-review-to-customer'),
    path('get_single_review_customer/<int:id_user>/<int:id_order>/', views.GetSingleReviewCustomer.as_view(),name='API-get-single-review-customer'),
    #

    # Vale
    path('items/list_all_items/', views.ListAllItems.as_view(), name='API-list-all-items'),
    path('items/<int:id_shop>/shop_all_items/', views.ShopAllItems.as_view(), name='API-shop-all-items'),
    path('items/<str:username_shop>/show_shop/', views.ShowShop.as_view(), name='API-show-shop'),
    path('items/<int:pk>/cart_orders/', views.CartOrders.as_view(), name='API-cart-orders'),
    path('id_items_from_orderitems/<int:pk>/', views.IdItemsFromOrderItems.as_view(), name='API-id-items-from-orderitems'),
    path('items/search/<int:pk>/<str:text>/', views.SearchItem.as_view(), name='API-search-item'),
    path('items/add_quantity/<int:pk>/<int:id_item>/<int:quantity>/', views.AddToCart.as_view(),
         name='API-add-to-cart'),

    path('items/<int:id_item>/delete/', views.DeleteItem.as_view(), name='API-delete-item-from-cart'),
    path('items/<int:id_item_to_delete>/deleteitemshop/', views.DeleteItemShop.as_view(), name='API-delete-item-shop'),
    path('items/<int:pk>/checkout/', views.Checkout, name='API-checkout'),
    path('items/<int:pk>/confirmcheckout/', views.ConfirmCheckout, name='API-confirm-checkout'),
    path('items/<int:id_item>/detail/', views.ItemDetail.as_view(), name='API-item-detail'),
    path('items/<int:id_item>/modifyitem/', views.ModifyItem.as_view(), name='API-modify-item'),
    # Fine

]

Marketplace/urls.py
from django.contrib import admin
#poichè si sta utilizzando Django >= 2.x si userà path e non url + pattern '' e non regexp r'^$' (analogamente nelle views)
from django.urls import path
from django.conf.urls import include    #aggiungo per poter usare la funzione include
from django.conf import settings
from django.conf.urls.static import static

# RICORDARSI: la / iniziale non va scritta all'inizio perchè si assume già inclusa nel path di grado inferiore
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),          #appena apro localhost:8000 parte la main.views
    path('users/', include('users.urls')),
    path('items/', include('items.urls')),
    path('review/', include('review.urls')),
    path('api/', include('API.urls')),

    path('api/rest-auth/', include("rest_auth.urls")),
    path('api/rest-auth/registration/', include("rest_auth.registration.urls")),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
#questo file non viene creato da django al momento della creazione dell'app ma deve essere creato manualmente
from django.urls import path
from . import views

app_name = 'users'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    # /users/login/
    path('login', views.login_all, name='login_all'),

    # /utenti/registrazione/
    # path('registration', views.registration, name='registration'),

    # path('test_login', views.test_login, name='test_login'),

    # /utenti/registrazione/normale
    path('normal_user_registration', views.normal_user_registration, name='normal_user_registration'),

    path('logout_user', views.logout_user, name='logout_user'),

    path('shop_registration', views.shop_registration, name='shop_registration'),
    path('modify_profile', views.modify_profile, name='modify_profile'),
    # path('modify_shop', views.modify_shop, name='modify_shop'),



    path('<int:oid>/prova_passaggio_interi', views.prova_passaggio_interi, name='prova_passaggio_interi'),
    path('insert_user_info', views.insert_user_info, name='insert_user_info'),
    path('insert_shop_info', views.insert_shop_info, name='insert_shop_info'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),


    path('home_for_user', views.home_for_user, name='home_for_user'),
    path('home_for_shop', views.home_for_shop, name='home_for_shop'),
    # path('prova_registrazione', views.prova_registrazione, name='prova_registrazione'),

    # /utenti/logout/
    #path('logout', views.logout, name='logout'),

]

users/views.py
import threading
from math import radians, sin, cos, atan2, sqrt
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from items.models import Order
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.http import Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms import modelformset_factory

from users.forms import NormalUserForm, UserForm, ShopProfileForm
from .models import GeneralUser
from . import models
from . import forms
import requests


def index(request):
    return render(request, 'users/home.html')  # pagina sito con barra di ricerca


# le views nelle funzioni sono ancora collegate a caso tra le pagine html esistenti solo per vedere se funzionavano le funzioni

def login_all(request):
    """
    Permette agli utenti di effettuare il login.

    :param request: request utente.
    :return: render della pagina login.
    """
    print("entra")
    if not request.user.is_authenticated:
        print("Non è autenticato")
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request,
                          user)  # [modifica]invece che loggare direttamente, creare un pop-up che avvisi l'utente che può loggarsi
                    # mostrare quindi la pagina principale, evitando di loggare in automatico
                    # controllo se ha fatto l'accesso un utente normale o un negozio

                    # return HttpResponse("L'utente " + request.user.username + " si è loggato con successo")
                    return HttpResponseRedirect(reverse('items:item_page'))
                else:
                    return render(request, 'users/login_page.html',
                                  {'error_message': 'Il tuo account è stato disattivato'})
            else:
                return render(request, 'users/login_page.html', {'error_message': 'Login invalido'})
        return render(request, 'users/login_page.html')
    else:
        # se l'utente è loggato gli faccio vedere la pagina items (andrà cambiata con la pagina per info utente-negozio) [modifica]
        return HttpResponseRedirect(reverse('items:item_page'))
        # return render(request, 'users/login_page.html', {'error_message': 'Immettere un utente e una password validi'})


# uguale alla registrazione dell'utente, se non cambia niente in futuro se ne può lasciare solo una
def shop_registration(request):
    form = UserForm(request.POST or None, oauth_user=0)

    if form.is_valid() and \
            not User.objects.filter(username=form.cleaned_data['username']).exists():
        shop = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        shop.set_password(password)
        shop.save()
        # serve così se per qualche motivo non va a buon fine l'inserimento successivo dei dati del GeneralUser,
        # posso inserirli in un secondo momento
        general_user = GeneralUser.objects.get_or_create(user=shop)[0]
        general_user.login_negozio = True
        general_user.save()
        shop = authenticate(username=username, password=password)
        if shop is not None:
            if shop.is_active:
                login(request, shop)
                return HttpResponseRedirect(reverse('users:insert_shop_info'))

    context = {
        "form": form,
    }

    return render(request, 'users/registration_page.html', context)


# Ricordarsi di mandare una email tra la registrazione iniziale e la compilazione del profilo
def normal_user_registration(request):
    """
    Permette agli utenti di registrare un account utente normale.

    :param request: request utente.
    :return: render della pagina di registrazione utente normale.
    """

    form = UserForm(request.POST or None, oauth_user=0)
    # normalform = NormalUserForm(request.POST or None, request.FILES or None)
    # form validi e utenti con lo stesso username non si sono già registrati
    if form.is_valid() and \
            not User.objects.filter(username=form.cleaned_data['username']).exists():

        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        print(user)
        general_user = GeneralUser.objects.get_or_create(user=user)[0]
        general_user.login_negozio = False
        general_user.save()
        print("passato oltre")
        '''try:
            profile.foto_profilo = request.FILES['foto_profilo']
        except Exception:
            profile.foto_profilo = None'''

        print("ha salvato")
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # return HttpResponseRedirect(reverse('users:insert_user_info', kwargs={'oid':user.pk}))
                return HttpResponseRedirect(reverse('users:insert_user_info'))
                # return HttpResponseRedirect(reverse('index'))
    else:
        print("i form non sono validi")
    context = {
        "form": form,
    }

    if not request.user.is_authenticated:
        # context['base_template'] = 'main/home.html'
        ...
    else:
        # return render(request, 'users/registration_page.html', context)
        # return HttpResponse("Effettuare prima il logout di: " + request.user.username)
        ...
    return render(request, 'users/registration_page.html', context)


@login_required(login_url='/users/login')  # aggiungere il controllo che sia un negozio e non un utente
def insert_shop_info(request):
    """
    [modifica]
1)    Creare anche la funzione edit shop_profile, questa viene chiamata dopo il login
  2) fare il controllo con oid passato anche tramite file html
    [fine-modifica]

    Permette agli utenti di modificare il proprio profilo, cambiando i loro dati.
    Verrà visualizzato dopo il primo login in modo tale da permettere all'utente di inserire tutti i dati.

    :param request: request utente.
    :param oid: id dell'utente di cui si vuole modificare il profilo (con controllo che sia == all'id
    dell'utente loggato).
    """

    oaut_user = False
    # if int(oid) == int(request.user.pk):

    # user_profile = User.objects.get(pk=oid)
    user_profile = User.objects.get(pk=request.user.pk)

    # if user_profile.has_usable_password():  # se la password è valida
    #     form = UserForm(data=request.POST or None, instance=request.user, oauth_user=0)
    # else:
    #     form = UserForm(data=request.POST or None, instance=request.user, oauth_user=1)
    #     oaut_user = True

    form = UserForm(data=request.POST or None, instance=user_profile, oauth_user=1)
    shopform = ShopProfileForm(request.POST or None, request.FILES or None)

    if shopform.is_valid():
        print("normal form validi")
        shop_profile = GeneralUser.objects.get_or_create(user=request.user)[0]
        try:
            shop_profile.foto_profilo = request.FILES['foto_profilo']
        except Exception:
            shop_profile.foto_profilo = None

        set_shop_info(shop_profile, shopform)
        print(user_profile)

        context={"user_profile": shop_profile}
        return render(request, 'main/home_for_shop.html', context)
        #return HttpResponse("Login effettuato con successo dall'utente: " + request.user.username +
                           # ' che abita in via: ' + shop_profile.indirizzo)
        # return HttpResponseRedirect(reverse('users:prova_passaggio_interi', kwargs={'oid':request.user.pk}))
    else:
        print("normal form NON validi")
    context = {
        "form": form,
        "profileForm": shopform,
    }

    # return render(request, 'users/'+ str(oid) +'/insert_info.html', context)
    return render(request, 'users/insert_shop_info.html', context)


def prova_passaggio_interi(request, oid):
    context = {
        'variabile': oid,
    }
    return render(request, 'users/prova_passaggio.html', context)


@login_required(login_url='/users/login')
def insert_user_info(request):
    """
    [modifica]
1)    Creare anche la funzione edit general_user, questa viene chiamata dopo il login
  2) fare il controllo con oid passato anche tramite file html
    [fine-modifica]

    Permette agli utenti di modificare il proprio profilo, cambiando i loro dati.
    Verrà visualizzato dopo il primo login in modo tale da permettere all'utente di inserire tutti i dati.

    :param request: request utente.
    :param oid: id dell'utente di cui si vuole modificare il profilo (con controllo che sia == all'id
    dell'utente loggato).
    """
    print("entra nel insert")
    oaut_user = False
    # if int(oid) == int(request.user.pk):
    print("CORRISPONDONO")

    # user_profile = User.objects.get(pk=oid)
    user_profile = User.objects.get(pk=request.user.pk)

    form = UserForm(data=request.POST or None, instance=user_profile, oauth_user=1)
    normalform = NormalUserForm(request.POST or None, request.FILES or None)

    if normalform.is_valid():
        print("normal form validi")
        general_user = GeneralUser.objects.get_or_create(user=request.user)[0]
        try:
            general_user.foto_profilo = request.FILES['foto_profilo']
        except Exception:
            general_user.foto_profilo = None

        set_user_info(general_user, normalform)
        order_qs = Order.objects.filter(
            user=request.user,
            ordered=False
        )

        if order_qs.exists():

users/templates/users/base_modifica_utente.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
        <div class="col-sm-10" > {{ field }}</div>
    </div>
{% endfor %}

{% for field in form_user_or_shop %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
        <div class="col-sm-10" id="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

users/templates/users/base_registrazione.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
        <div class="col-sm-10" > {{ field }}</div>
    </div>
{% endfor %}

{% for field in profileForm %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>

        <label class="control-label col-sm-2" for="user">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

users/templates/users/checkLogin.html
{% comment %} Welcome page of the portal. {% endcomment %}
{% block title %} Welcome page {% endblock %}
{% block content %}
<section>
<h2>Welcome {{ request.user.username | capfirst }}</h2>
<p>This is the entry page of the Web portal. Thanks for logging in.</p>
</section>
<!--    <li><a href="{% url 'logout_view' %}">Logout</a></li>-->
{% endblock %}

users/templates/users/insert_shop_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'users/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Insert shop info{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico file style.css presente in static -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico link a Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico ????? -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<!----------------------------------------- INSERT_INFO  ---------------------------------------->
  {% block insert_user_info %}
  <div class="insert_page">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <div class="form_container_modify_info">
                    <div class="form-btn">
                        <span>Insert Shop Info</span>
                    </div>

                    <form id="RegFormShop2" action="{% url 'users:insert_shop_info'%}" method="post">
                        {% csrf_token %}
                        {% include 'users/base_registrazione.html' %}
                        <button type="submit" class="btn">Prosegui</button>
                    </form>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
                        <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
                        <script type="text/javascript" src="{% static 'modify_user_form_validator.js' %}"></script>
                </div>
            </div>
        </div>
    </div>
  </div>
  {% endblock %}
</body>
</html>

users/templates/users/logout_effettuato.html
{% comment %} Logout effettuato con successo {% endcomment %}

users/templates/users/modify_shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Modify_Profile{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    {% block menu_id %}
    <li><a href="{% url 'users:home_for_shop' %}">Home</a></li>
    {% endblock %}

    {% block modify_profile %}
    <div class="modify_user_page">
      <div class="container">
          <h2 id="title">Modify Shop with Name:{{ user_profile }} and Id: {{ user_profile.id }}</h2>
          <div class="row">
              <div class="col-2">
                  <div class="form_container_modify_user_page">
                      <div class="form-btn">
                          <span>Modify Shop Info</span>
                      </div>
                      <form id="RegFormShop2" method="post" action="{% url 'users:modify_shop' %}"enctype="multipart/form-data">
                          {% csrf_token %}
                          {% include 'users/base_modifica_negozio.html' %}
                          <button type="submit" class="btn" value="Submit">Submit</button>
                      </form>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
                        <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
                        <script type="text/javascript" src="{% static 'modify_user_form_validator.js' %}"></script>
                  </div>
              </div>
          </div>
      </div>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/overview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Capability overview</title>
</head>
<body>
<form action="" method="post">
    {{ formset.management_form }}
    {% csrf_token %}
    <ul>
    {% for form in formset %}
        <li>
        {{ form }}
        </li>
    {% endfor %}
    </ul>
    <input type="submit" name="save" value="Submit" />
</form>
</body>
</html>

users/templates/users/prova_passaggio.html
                        <form id="RegFormShop" action="{% url 'users:normal_user_registration' oid=oid_value%}" method="post">
                            {% csrf_token %}
                             {% include 'users/base_registrazione.html' %}
                            {{oid}}
<!--                            <input type="text" placeholder="Username">-->
<!--                            <input type="email" placeholder="Email">-->
<!--                            <input type="password" placeholder="Password">-->

                            <button type="submit" class="btn">Register Shop</button>
                        </form>

users/templates/users/registration_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Registrazione{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

<!----------------------------------------- SCRITTE INIZIALI ---------------------------------------->
    {% block menu_id %}
    <li><a href="{% url 'index' %}">Home</a></li>
    {% endblock %}

<!----------------------------------------- LOGIN_PAGE ---------------------------------------->
    {% block insert_info %}
    <div class="registration_page">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <div class="form-container">
                        <div class="form-btn">
                            <span onclick="register_user()">Utente</span>
                            <span onclick="register_shop()">Negozio</span>
                            <hr id="Indicator">
                        </div>

                        <form id="RegFormUser" action="{% url 'users:normal_user_registration'%}" method="post">
                            {% csrf_token %}
                            {% include 'users/base_registrazione.html' %}
<!--                            <input type="text" name="username" class="input-box" placeholder="Username22" maxlength="15">-->
<!--                            <input type="password" name="password" class="input-box" placeholder="Password22" maxlength="15">-->

                            <button type="submit" class="btn_modify">Registra Utente</button>
                        </form>

                        <form id="RegFormShop" action="{% url 'users:shop_registration'%}" method="post">
                            {% csrf_token %}
                             {% include 'users/base_registrazione.html' %}
<!--                            <input type="text" placeholder="Username">-->
<!--                            <input type="email" placeholder="Email">-->
<!--                            <input type="password" placeholder="Password">-->

                            <button type="submit" class="btn_modify">Registra Negozio</button>
                        </form>
                        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
                        <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
                        <script type="text/javascript" src="{% static 'user_form_validator.js' %}"></script>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!----------------------------------------- Js ToggleMenu ---------------------------------------->
   <script>

       var LoginForm = document.getElementById("LoginForm");
       var RegForm = document.getElementById("RegForm");
       var Indicator = document.getElementById("Indicator");

       function register_user(){
         RegFormShop.style.transform = "translateX(402px)";
         RegFormUser.style.transform = "translateX(402px)";
         Indicator.style.transform = "translateX(0px)";
       }


       function register_shop(){
         RegFormShop.style.transform = "translateX(0px)";
         RegFormUser.style.transform = "translateX(0px)";
         Indicator.style.transform = "translateX(100px)";
       }



   </script>
    {% endblock %}
</body>
</html>