API/urls.py
from . import views
from django.urls import path
app_name = 'API'
from .views import *

"""
Per chiamare queste funzioni è necessario mettere nell'url prima la stringa http://127.0.0.1:5000/api/
"""
urlpatterns = [

    path('', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/find/<str:name>/', views.FindUser.as_view(), name='API-cerca-utente'),
    path('users/register/normaluser/', views.RegisterNormalUserFromMobilePhone.as_view(), name='API-registra-utente-normale'),
    path('users/register/shopuser/', views.RegisterShopUserFromMobilePhone.as_view(), name='API-registra-negozio'),
    path('users/profile/<int:pk>/', views.UserInfoLogin.as_view(), name='API-user-info'),
    path('users/profile/', views.ModifyInfoLoginUser.as_view(), name='API-user-modify-info'),

    # per utente
    path('reviews_customer/<int:pk>/', views.ReturnReviewCustomer.as_view(), name='API-reviews-customer'),
    path('orders_customer/<int:pk>/', views.ReturnOrderCustomer.as_view(), name='API-orders-customer'),
    path('order_items_ref_code/<str:order_items_id>/', views.ReturnOrderItems.as_view(), name='API-orderitems-customer'),
    path('items_from_orderitems/<str:order_items_id>/', views.ReturnItemsFromOrderItems.as_view(), name='API-items-from-orderitemscustomer'),
    path('items_from_orderitems_filtered/<str:order_items_id>/<str:name_shop>/', views.ReturnItemsFromOrderItemsFiltered.as_view(), name='API-items-from-orderitemscustomer-filtered'),
    path('get_review_item/<str:order_item_id>/<str:item_selected_id>/', views.GetSingleReviewItem.as_view(), name='API-get-review-item-order'),
    path('leave_review_item/<str:order_item_id>/<str:item_selected_id>/', views.CreateReviewItem.as_view(), name='API-leave-review-item'),
    # path('orderitem_item/<str:order_items_id>/<str:id_shop>/', views.ReturnOrderItemsAndOrderItems.as_view(), name='API-orderitem-item'),
    path('check_existing_username/<str:username_to_check>/', check_existing_username),
    path('check_existing_username_ajax/', check_existing_username_ajax),

    # se devo aggiungere la mail prima controllo che non esista già un waituser con quell'username e quella password
    # e se non esiste lo creo e con un altro fetch aggiungo la password
    path('create_waituser/', views.CreateWaitUser.as_view(), name='API-create-waituser'),
    path('insert_email/<int:item_selected_id>/', views.InsertEmail.as_view(), name='API-insert-email'),



    # per Shop
    path('orders_shop/', views.ReturnOrderDoneByCustomer.as_view(), name='API-orders-shop'),
    path('items_booked/<str:order_items_id>/', views.ReturnItemsBooked.as_view(), name='API-items-shop'),
    path('travel_time/<str:username_shop>/', views.ReturnTimeUserShop, name='API-time-travel'),
    # path('upload_image/<str:id_shop>/', views.UploadItem.as_view(), name='API-upload-item'),
    path('insert_item/', views.InsertNewItem.as_view(), name='API-insert-item'),

    # *** review for/to shop
    path('review_shop/<str:username_shop>/', views.ReturnReviewShop.as_view(), name='API-review-shop'),
    path('review_from_customer_to_shop/<str:username_shop>/', views.CreateReviewForShop.as_view(), name='API-new-review-shop'),
    path('get_single_review_shop/<str:username_shop>/', views.GetSingleReviewShop.as_view(), name='API-get-single-review-left-to-shop'),

    # *** review for/to customer
    path('review_from_shop_to_customer/<int:id_user>/<int:id_order>/', views.CreateReviewForCustomer.as_view(),name='API-new-review-to-customer'),
    path('get_single_review_customer/<int:id_user>/<int:id_order>/', views.GetSingleReviewCustomer.as_view(),name='API-get-single-review-customer'),
    #

    # Vale
    path('items/list_all_items/', views.ListAllItems.as_view(), name='API-list-all-items'),
    path('items/<int:id_shop>/shop_all_items/', views.ShopAllItems.as_view(), name='API-shop-all-items'),
    path('items/<str:username_shop>/show_shop/', views.ShowShop.as_view(), name='API-show-shop'),
    path('items/<int:pk>/cart_orders/', views.CartOrders.as_view(), name='API-cart-orders'),
    path('id_items_from_orderitems/<int:pk>/', views.IdItemsFromOrderItems.as_view(), name='API-id-items-from-orderitems'),
    path('items/search/<int:pk>/<str:text>/', views.SearchItem.as_view(), name='API-search-item'),
    path('items/add_quantity/<int:pk>/<int:id_item>/<int:quantity>/', views.AddToCart.as_view(),
         name='API-add-to-cart'),

    path('items/<int:id_item>/delete/', views.DeleteItem.as_view(), name='API-delete-item-from-cart'),
    path('items/<int:id_item_to_delete>/deleteitemshop/', views.DeleteItemShop.as_view(), name='API-delete-item-shop'),
    path('items/<int:pk>/checkout/', views.Checkout, name='API-checkout'),
    path('items/<int:pk>/confirmcheckout/', views.ConfirmCheckout, name='API-confirm-checkout'),
    path('items/<int:id_item>/detail/', views.ItemDetail.as_view(), name='API-item-detail'),
    path('items/<int:id_item>/modifyitem/', views.ModifyItem.as_view(), name='API-modify-item'),
    # Fine

]

Marketplace/urls.py
from django.contrib import admin
#poichè si sta utilizzando Django >= 2.x si userà path e non url + pattern '' e non regexp r'^$' (analogamente nelle views)
from django.urls import path
from django.conf.urls import include    #aggiungo per poter usare la funzione include
from django.conf import settings
from django.conf.urls.static import static

# RICORDARSI: la / iniziale non va scritta all'inizio perchè si assume già inclusa nel path di grado inferiore
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),          #appena apro localhost:8000 parte la main.views
    path('users/', include('users.urls')),
    path('items/', include('items.urls')),
    path('review/', include('review.urls')),
    path('api/', include('API.urls')),

    path('api/rest-auth/', include("rest_auth.urls")),
    path('api/rest-auth/registration/', include("rest_auth.registration.urls")),

    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from . import views

app_name = 'items'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    path('', views.item_page, name='item_page'),

    path('insert_item', views.insert_item, name='insert_item'),

    path('insert_email/<str:item_selected_id>', views.insert_email, name='insert_email'),

    path('<int:item_selected_id>/computeTime', views.computeTime, name='computeTime'),

    path('<int:item_selected_id>/show_feedback_item', views.show_feedback_item, name='show_feedback_item'),

    path('<int:shop_selected_id>/show_reviews_shop', views.show_reviews_shop, name='show_reviews_shop'),

    path('checkout', views.checkout, name='checkout'),

    path('<int:item_selected_id>/', views.buy_page, name='buy_page'),

    path('show_shop/<str:username_shop>', views.show_shop, name='show_shop'),

    #/annunci/#annuncio/modifica/
    path('<int:item_selected_id>/modify', views.modify_item, name='modify_item'),

    #/annunci/#annuncio/elimina/
    path('<int:item_selected_id>/delete', views.delete_item, name='delete_item'),

    #/annunci/#annuncio/add_to_cart/
    path('<int:item_selected_id>/add_to_cart', views.add_to_cart, name='add_to_cart'),

    path('go_to_cart', views.go_to_cart, name='go_to_cart'),

    path('<int:item_selected_id>/remove_single_item_from_cart', views.remove_single_item_from_cart, name='remove_single_item_from_cart'),

    path('<int:item_selected_id>/remove_entire_item_from_cart', views.remove_entire_item_from_cart, name='remove_entire_item_from_cart'),

    path('view_order', views.view_order, name='view_order'),

    path('search/', views.search, name='search'),
]

main/urls.py
#questo file non viene creato da Django al momento della creazione dell'app ma deve essere creato manualmente
from django.urls import path
from . import views

urlpatterns = [

    #views.name = name
    path('', views.index, name='index'),    #quando viene riconosciuto il path localhost:8000 vengo reindirizzato alla funzione index presente in views.py di main

    #/main/login/
    # path('login', views.login_page, name='login_page'),

    #/main/registration/
    path('registration', views.registration_page, name='registration_page'),

    #/main/cart-> DA CAMBIAREEEEEEEEEE !!!!! NON VOGLIO IL CARRRELLO VUOTO NELLA HOME è solo x vedere la grafica
    path('empty_cart', views.empty_cart, name='empty_cart'),

    path('contact', views.contact, name='contact'),

    path('mostra_logout_avvenuto', views.mostra_logout_avvenuto, name='mostra_logout_avvenuto'),
    path('autenticato', views.autenticato, name='autenticato'),
]

review/urls.py
from django.urls import path
from . import views

app_name = 'review'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    path('show_items_to_review', views.show_items_to_review, name='show_items_to_review'),

    path('show_order_done_by_customer', views.show_order_done_by_customer, name='show_order_done_by_customer'),

    path('<int:item_selected_id>/<int:order_item_id>/add_review_item', views.add_review_item, name='add_review_item'),

    path('<int:item_selected_id>/<int:order_item_id>/show_item_reviewed', views.show_item_reviewed, name='show_item_reviewed'),

    path('<int:receiver_id>/<int:order_item_id>/show_customers_reviewed', views.show_customers_reviewed, name='show_customers_reviewed'),

    path('<int:shop_selected_id>/add_review_shop', views.add_review_shop, name='add_review_shop'),

    path('<int:order_id>/<int:customer_id>/add_review_customer', views.add_review_customer, name='add_review_customer'),


]

users/urls.py
#questo file non viene creato da django al momento della creazione dell'app ma deve essere creato manualmente
from django.urls import path
from . import views

app_name = 'users'  #fondamentale per poter usare ad es. {% url 'users:login_all'%}

urlpatterns = [

    # /users/login/
    path('login', views.login_all, name='login_all'),

    # /utenti/registrazione/
    # path('registration', views.registration, name='registration'),

    # path('test_login', views.test_login, name='test_login'),

    # /utenti/registrazione/normale
    path('normal_user_registration', views.normal_user_registration, name='normal_user_registration'),

    path('logout_user', views.logout_user, name='logout_user'),

    path('shop_registration', views.shop_registration, name='shop_registration'),
    path('modify_profile', views.modify_profile, name='modify_profile'),
    # path('modify_shop', views.modify_shop, name='modify_shop'),



    path('<int:oid>/prova_passaggio_interi', views.prova_passaggio_interi, name='prova_passaggio_interi'),
    path('insert_user_info', views.insert_user_info, name='insert_user_info'),
    path('insert_shop_info', views.insert_shop_info, name='insert_shop_info'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),
    # path('show_distance_shops', views.show_distance_shops, name='show_distance_shops'),


    path('home_for_user', views.home_for_user, name='home_for_user'),
    path('home_for_shop', views.home_for_shop, name='home_for_shop'),
    # path('prova_registrazione', views.prova_registrazione, name='prova_registrazione'),

    # /utenti/logout/
    #path('logout', views.logout, name='logout'),

]

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User

def index(request):
    return render(request, 'main/home.html')    #pagina principale del sito




def autenticato(request):
    return render(request, 'main/autenticato.html')

#def handler404(request):
    #add something
    #return render(request, '404.html', status=404, context=context)

# def login_page(request):
#     return render(request, 'users/login_page.html')

def registration_page(request):
    return render(request, 'users/registration_page.html')

def empty_cart(request):
    return render(request, 'main/empty_cart.html')

def mostra_logout_avvenuto(request):
    return render(request, 'users/logout_effettuato.html')

def contact(request):
    return render(request, 'main/contact.html')

main/templates/main/autenticato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Ti sei autenticato, adesso puoi cercare i prodotti{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico file style.css presente in static -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico link a Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico ????? -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

</html>

main/templates/main/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Contact{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<!----------------------------------------- SCRITTE INIZIALI ---------------------------------------->
    {% block menu_id %}
<li><a href="{% url 'index' %}">Home</a></li>
    {% endblock %}

    {% block contact %}
    <section class>





    </section>
    {% endblock %}
</body>
</html>

main/templates/main/empty_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- login_page.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Empty_Cart{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block empty_cart %}
    <div class="empty_cart">
        <div class="empty-container">
                <div class="col-empty">
                    <div class="row-empty-1">
                        <img src="{% static 'images/empty_cart.png' %}" class="empty_cart-img">
                    </div>
                    <div class="row-empty-2">
                        <h2>Il tuo carrello è vuoto!</h2>
                        <small>Accedi o Registrati per visualizzare il tuo carrello<br>
                        e dai inizio agli acquisti!<br>
                        </small>
                    </div>
                    <div class="row-empty-3">
                        <a href="{% url 'users:login_all' %}" class="btn">Accedi</a>
                    </div>
                </div>
        </div>
    </div>
    {% endblock %}
</body>
</html>

main/templates/main/home_for_shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width= device-width, initial-scale=1.0">

    <!-- home.html è un'estensione di base.html -->
    {% extends 'main/base.html' %}

    <!-- ridefinisco title -->
    <title>{% block title %}Home_For_Shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- carico la directory static per poter usare i suoi file -->
    {% load static %}

    <!-- carico link a Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- carico file style.css presente in static -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- carico link a Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,600&display=swap" rel="stylesheet">

    <!-- carico link a font -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<!----------------------------------------- SCRITTE INIZIALI ---------------------------------------->
    {% block menu_id %}
        <li> <a href="{% url 'users:modify_profile' %}">
            <span class="badge bg-danger bg-secondary"></span>
            <img src="{% static 'images/edit-profile-icon.jpg'%}" width="30px" height="30px">
        </a></li>
        <li><a href="{% url 'items:insert_item' %}">Aggiungi oggetto</a></li>
        <li><a href="{% url 'review:show_order_done_by_customer' %}">Recensioni Ordini</a></li>
        <li><a href="{% url 'items:item_page' %}">Oggetti Negozio</a></li>
    {% block logout %}
        <div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel">Logout for {{user_profile}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">Do you really want to logout?</div>
              <div class="modal-footer">
                <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Yes</button>&ensp;
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">No</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel2">Logout succesfull</h5>
              </div>
              <div class="modal-body">{{user_profile}} you are succesfully logout</div>
              <div class="modal-footer">
                <a href="{% url 'users:logout_user' %}"type="button" class="btn primary">Ok</a>
              </div>
            </div>
          </div>
        </div>
<li><a data-bs-toggle="modal" href="#exampleModalToggle" role="button">Logout</a></li>
        {% endblock %}
    {% endblock %}

<!----------------------------------------- MENU ---------------------------------------->
    {% block first_row %}
    <div style="padding-left: 150px; margin-right: 0px; background: rgba(238,238,238,0.7);" class="row">
        <div style="padding-left: 0px" class="container text-center">
        {% if user_profile is not None %}
        <h3 id="title">Benvenuto: {{ user_profile }}</h3>
        {% endif %}
    </div>
        <div class="col-2">
            <h1>Give Your Workout<br>A New Style!</h1>
            <p>Success isn't always about greatness. It's about
            consistency.Consistent<br>hard work gains success. Greatness will come.</p>
            <a href="" class="btn">Explore Now &#10148;</a>
        </div>
        <div class="col-2">
            <img src="{% static 'images/first.jpg' %}">
        </div>
    </div>
    {% endblock %}

<!----------------------------------------- IMMAGE GALLERY ---------------------------------------->
    {% block gallery %}
    <div class="container_gallery">
        <div class="col_gallery">
            <h2>BIKE</h2>
            <div class="caption">
                <p>Strenght does not come <br>from the physical capacity.</p>
                <button type="button">Know More</button>
            </div>
            <img src="{% static 'images/gallery_1.png' %}">
        </div>

        <div class="col_gallery">
            <h2>MUSIC</h2>
            <div class="caption">
                <p>Strenght does not come <br>from the physical capacity.</p>
                <button type="button">Know More</button>
            </div>
            <img src="{% static 'images/gallery_2.png' %}">
        </div>

        <div class="col_gallery">
            <h2>COMPUTER</h2>
            <div class="caption">
                <p>Strenght does not come <br>from the physical capacity.</p>
                <button type="button">Know More</button>
            </div>
            <img src="{% static 'images/gallery_3.png' %}">
        </div>
    </div>
    {% endblock %}
<!----------------------------------------- CAROUSEL ---------------------------------------->
    {% block carousel %}
    <div class="bootstramp_carousel">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
        <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="1500">
              <img src="{% static 'images/carousel_1.png' %}" width="1500px" height="600px">
            </div>
            <div class="carousel-item" data-bs-interval="1500">
              <img src="{% static 'images/carousel_2.png' %}" width="1500px" height="600px">
            </div>
            <div class="carousel-item" data-bs-interval="1500">
              <img src="{% static 'images/carousel_3.png' %}" width="1500px" height="600px">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
    </div>
    {% endblock %}
<!----------------------------------------- OFFER ---------------------------------------->
    {% block offer %}
    <div class="offer">
        <div class="small-container">
            <div class="row">
                <div class="col-2">
                    <img src="{% static 'images/offer.png' %}" class="offer-img">
                </div>
                <div class="col-2">
                    <p>Exclusively Available on NOME SITO</p>
                    <h1>Smart Brand 4</h1>
                    <small>The Mi Smart Band 4 features a 39.9% larger than AMOLED color full-touch
                        display<br>with adjustable brightness,so everything is clear as can be.<br>
                    </small>
                    <a href="" class="btn">Buy Now &#10148;</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

<!----------------------------------------- TESTIMONIAL ---------------------------------------->
    {% block testimonial %}
    <div class="testimonial">
        <div class="small-container">
            <div class="row">
                <!-- user 1 -->
                <div class="col-3">
                    <i class="fa fa-quote-left"></i>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        Lorem Ipsum has been the industry's standard dummy text ever</p>
                    <div class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                    </div>
                    <img src="{% static 'images/user_1.png' %}">
                    <h3>Sean Parker</h3>
                </div>

                <!-- user 2 -->
                <div class="col-3">
                    <i class="fa fa-quote-left"></i>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        Lorem Ipsum has been the industry's standard dummy text ever</p>
                    <div class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                    </div>
                    <img src="{% static 'images/user_2.png' %}">
                    <h3>Mike Smith</h3>
                </div>

                <!-- user 3 -->
                <div class="col-3">
                    <i class="fa fa-quote-left"></i>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        Lorem Ipsum has been the industry's standard dummy text ever</p>
                    <div class="rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o"></i>
                    </div>
                    <img src="{% static 'images/user_3.png' %}">
                    <h3>Mabel Joe</h3>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
<!----------------------------------------- BRANDS ---------------------------------------->
    {% block brands %}
    <div class="brands">
        <div class="small-container">
            <div class="row">
                <div class="col-4">
                    <img src="{% static 'images/brand_1.PNG' %}">
                </div>
                <div class="col-4">
                    <img src="{% static 'images/brand_2.PNG' %}">
                </div>
                <div class="col-4">
                    <img src="{% static 'images/brand_3.PNG' %}">
                </div>
                <div class="col-4">
                    <img src="{% static 'images/brand_4.PNG' %}">
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

<!----------------------------------------- END SITE ---------------------------------------->
</body>
</html>